# Boston 311 Analysis - Python Project Configuration

[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_no_return = true
ignore_missing_imports = true
# Relaxed settings for data science/analytics projects
disallow_untyped_defs = false
disallow_incomplete_defs = false
no_strict_optional = true

[tool.pylint.messages_control]
max-line-length = 100
disable = [
    "C0103",  # Invalid name (for short variable names like df)
    "R0913",  # Too many arguments
    "R0914",  # Too many local variables
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
